### ISSUE TITLE
Client joined formatting problem

### ISSUE THREAD

**Issue by tommyriska** [tommyriska/GoChat#23]
Upon new client connection, users in all rooms besides Lobby gets a message that says: "[newuser] has left". Clients in the lobby room gets the right message: "[newclient] joined Lobby".
In the window down to the left you see a client 2 that is in room TestRoom. Then when client 3(bottom right) joins the server i.e joins the lobby, client 2 gets a message saying that client 3 has left. This message should not be printed since they're not in the same room. 

![2017-05-28--1495971209_1440x900_scrot](https://cloud.githubusercontent.com/assets/15278093/26528379/deabf846-43aa-11e7-9a90-245fc882e087.png)

**Comment by adneja** [comment]
steng det ner
